all: true
check-coverage: true
include:
  - src
statements: 62
branches: 51
functions: 65
lines: 61
watermarks:
  branches: [90, 100]
  lines: [90, 100]
  functions: [90, 100]
  statements: [90, 100]

