all: true
check-coverage: true
include:
  - src
statements: 76
branches: 63
functions: 72
lines: 75
watermarks:
  branches: [90, 100]
  lines: [90, 100]
  functions: [90, 100]
  statements: [90, 100]

